
<!DOCTYPE html>
<html>

<?php


	require_once("../Functions/pagina3.php");	
	//loadMainLayout_Header(); 
	
	
	//require_once("../Functions/ReadMenus.php");
	//readMainMenu();
	
	//phpinfo();
	
	
	 
	$x = 1; 

	while($x <= 5) {
		echo "The number is: $x <br>";
		$x++;
	} 
	 
	 
	 echo "The number is: $x <br>";
	 echo "The number is: $x <br>";
	 echo "The number is: $x <br>";
	 echo "The number is: $x <br>";
	 echo "The number is: $x <br>";
         
         echo "The number is: $x <br>";
	 
	
	
	
	
?>
</html>